# -*- coding: utf-8 -*-
"""yolo_clustering_func

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EqrBoG9biLJIpLncaW10t173NeutXMw8
"""

from ultralytics import YOLO
import cv2
import numpy as np
import torch
from sklearn.cluster import KMeans


# Load YOLO model
model = YOLO("yolov8l.pt")
yolo_model = model.model

# Extract backbone
backbone = yolo_model.model[:8]   #size of backbone
backbone.eval()


def preprocess_image(image):

    image_resized = cv2.resize(image, (640,640))

    x = torch.from_numpy(image_resized).permute(2,0,1).unsqueeze(0)
    x = x.float() / 255.0

    return x, image_resized


def extract_features(backbone, x):

    with torch.no_grad():
        features = backbone(x)

    feat = features.squeeze(0).permute(1,2,0).detach().cpu().numpy()

    return feat


def cluster_features(feature_map, k=4):

    H, W, C = feature_map.shape

    pixels = feature_map.reshape(-1, C)

    kmeans = KMeans(n_clusters=k, random_state=42)

    labels = kmeans.fit_predict(pixels)

    seg_map = labels.reshape(H, W)

    return seg_map


def find_road_cluster(seg_map):

    H, W = seg_map.shape
    clusters = np.unique(seg_map)

    scores = []

    for c in clusters:

        mask = seg_map == c
        lower_half = mask[H//2:, :]

        scores.append(lower_half.sum())

    road_cluster = clusters[np.argmax(scores)]

    return road_cluster


def visualize_clusters(image, seg_map, k):

    # Resize cluster map to match image size
    seg_resized = cv2.resize(
        seg_map.astype("uint8"),
        (image.shape[1], image.shape[0]),
        interpolation=cv2.INTER_NEAREST
    )

    # Generate consistent colors
    np.random.seed(42)
    colors = np.random.randint(0,255,(k,3))

    # Convert cluster IDs → RGB colors
    cluster_color_map = colors[seg_resized]

    # Blend with original image
    overlay = (0.6 * image + 0.4 * cluster_color_map).astype("uint8")

    return overlay


def run_yolo_clustering_func(image, backbone, k=4):

    x, image_resized = preprocess_image(image)

    features = extract_features(backbone, x)

    seg_map = cluster_features(features, k)

    road_cluster = find_road_cluster(seg_map)

    road_mask = (seg_map == road_cluster)

    road_mask_resized = cv2.resize(
        road_mask.astype("uint8"),
        (image.shape[1], image.shape[0]),
        interpolation=cv2.INTER_NEAREST
    )

    cluster_img = visualize_clusters(image, seg_map, k)

    return seg_map, road_cluster, road_mask_resized, cluster_img