{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyP40wRipDuUnFXPqBDjY+3L",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Daanish-Jain/drone-path/blob/main/yolo_clustering_func.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from ultralytics import YOLO\n",
        "import cv2\n",
        "import numpy as np\n",
        "import torch\n",
        "from sklearn.cluster import KMeans\n",
        "\n",
        "\n",
        "# Load YOLO model\n",
        "model = YOLO(\"yolov8l.pt\")\n",
        "yolo_model = model.model\n",
        "\n",
        "# Extract backbone\n",
        "backbone = yolo_model.model[:10]   #size of backbone\n",
        "backbone.eval()\n",
        "\n",
        "\n",
        "def preprocess_image(image):\n",
        "\n",
        "    image_resized = cv2.resize(image, (640,640))\n",
        "\n",
        "    x = torch.from_numpy(image_resized).permute(2,0,1).unsqueeze(0)\n",
        "    x = x.float() / 255.0\n",
        "\n",
        "    return x, image_resized\n",
        "\n",
        "\n",
        "def extract_features(backbone, x):\n",
        "\n",
        "    with torch.no_grad():\n",
        "        features = backbone(x)\n",
        "\n",
        "    feat = features.squeeze(0).permute(1,2,0).detach().cpu().numpy()\n",
        "\n",
        "    return feat\n",
        "\n",
        "\n",
        "def cluster_features(feature_map, k=4):\n",
        "\n",
        "    H, W, C = feature_map.shape\n",
        "\n",
        "    pixels = feature_map.reshape(-1, C)\n",
        "\n",
        "    kmeans = KMeans(n_clusters=k, random_state=42)\n",
        "\n",
        "    labels = kmeans.fit_predict(pixels)\n",
        "\n",
        "    seg_map = labels.reshape(H, W)\n",
        "\n",
        "    return seg_map\n",
        "\n",
        "\n",
        "def find_road_cluster(seg_map):\n",
        "\n",
        "    H, W = seg_map.shape\n",
        "    clusters = np.unique(seg_map)\n",
        "\n",
        "    scores = []\n",
        "\n",
        "    for c in clusters:\n",
        "\n",
        "        mask = seg_map == c\n",
        "        lower_half = mask[H//2:, :]\n",
        "\n",
        "        scores.append(lower_half.sum())\n",
        "\n",
        "    road_cluster = clusters[np.argmax(scores)]\n",
        "\n",
        "    return road_cluster\n",
        "\n",
        "\n",
        "def visualize_clusters(image, seg_map, k):\n",
        "\n",
        "    # Resize cluster map to match image size\n",
        "    seg_resized = cv2.resize(\n",
        "        seg_map.astype(\"uint8\"),\n",
        "        (image.shape[1], image.shape[0]),\n",
        "        interpolation=cv2.INTER_NEAREST\n",
        "    )\n",
        "\n",
        "    # Generate consistent colors\n",
        "    np.random.seed(42)\n",
        "    colors = np.random.randint(0,255,(k,3))\n",
        "\n",
        "    # Convert cluster IDs → RGB colors\n",
        "    cluster_color_map = colors[seg_resized]\n",
        "\n",
        "    # Blend with original image\n",
        "    overlay = (0.6 * image + 0.4 * cluster_color_map).astype(\"uint8\")\n",
        "\n",
        "    return overlay\n",
        "\n",
        "\n",
        "def run_yolo_clustering_func(image, backbone, k=4):\n",
        "\n",
        "    x, image_resized = preprocess_image(image)\n",
        "\n",
        "    features = extract_features(backbone, x)\n",
        "\n",
        "    seg_map = cluster_features(features, k)\n",
        "\n",
        "    road_cluster = find_road_cluster(seg_map)\n",
        "\n",
        "    road_mask = (seg_map == road_cluster)\n",
        "\n",
        "    road_mask_resized = cv2.resize(\n",
        "        road_mask.astype(\"uint8\"),\n",
        "        (image.shape[1], image.shape[0]),\n",
        "        interpolation=cv2.INTER_NEAREST\n",
        "    )\n",
        "\n",
        "    cluster_img = visualize_clusters(image, seg_map, k)\n",
        "\n",
        "    return seg_map, road_cluster, road_mask_resized, cluster_img"
      ],
      "metadata": {
        "id": "PkY9ZxkboDSG"
      },
      "execution_count": 18,
      "outputs": []
    }
  ]
}